### ISSUE TITLE
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

### ISSUE THREAD

**Issue by Eduardneu** [JecaTosovic/ConservedWaterSearch#4]
Hi,

I tried to install the package but encountered this error: 

```
      building 'hdbscan._hdbscan_tree' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
```

There is a fix for this described here on stackoverflow:

https://stackoverflow.com/questions/64261546/how-to-solve-error-microsoft-visual-c-14-0-or-greater-is-required-when-inst

Cheers

**Comment by JecaTosovic** [comment]
HDBSCAN requires C++ when installed from pip. We should add a small section on installation documentation that documents that C++ compiler is needed.
Thanks for reporting this.
